version: "3.8"

services:
  ollama:
    image: ghcr.io/ollama/ollama:latest
    command: serve --listen 0.0.0.0:11434
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama/models

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama